//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.efatura.gov.tr/package-namespace")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.efatura.gov.tr/package-namespace", IsNullable=false)]
public partial class Package {

    private static XmlSerializerNamespaces xmlns = new XmlSerializerNamespaces(new[]
        {
                new XmlQualifiedName("ef","http://www.efatura.gov.tr/package-namespace"),
                //new XmlQualifiedName("xsi","http://www.w3.org/2001/XMLSchema-instance"), 
                //new XmlQualifiedName("xsi","http://www.w3.org/2001/XMLSchema-instance"),
            });

    /// <summary>
    /// Takes care of namespace prefix in saved xml documents
    /// </summary>
    [System.Xml.Serialization.XmlNamespaceDeclarations()]
    public XmlSerializerNamespaces Xmlns = xmlns;

    private PackageElements[] elementsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Elements", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PackageElements[] Elements {
        get {
            return this.elementsField;
        }
        set {
            this.elementsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.efatura.gov.tr/package-namespace")]
public partial class PackageElements {
    
    private string elementTypeField;
    
    private int elementCountField;
    
    private PackageElementsElementList elementListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElementType {
        get {
            return this.elementTypeField;
        }
        set {
            this.elementTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ElementCount {
        get {
            return this.elementCountField;
        }
        set {
            this.elementCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PackageElementsElementList ElementList {
        get {
            return this.elementListField;
        }
        set {
            this.elementListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.efatura.gov.tr/package-namespace")]
public partial class PackageElementsElementList {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}
