//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EFaturaSoapBinding", Namespace="http://gib.gov.tr/vedop3/eFatura")]
public partial class EFatura : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback sendDocumentOperationCompleted;
    
    private System.Threading.SendOrPostCallback getApplicationResponseOperationCompleted;
    
    /// <remarks/>
    public EFatura() {
        this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
        this.Url = "http://merkeztest.efatura.gov.tr/EFaturaMerkez/services/EFatura";
    }
    
    /// <remarks/>
    public event sendDocumentCompletedEventHandler sendDocumentCompleted;
    
    /// <remarks/>
    public event getApplicationResponseCompletedEventHandler getApplicationResponseCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("sendDocument", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("documentResponse", Namespace="http://gib.gov.tr/vedop3/eFatura")]
    public documentReturnType sendDocument([System.Xml.Serialization.XmlElementAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")] documentType documentRequest) {
        object[] results = this.Invoke("sendDocument", new object[] {
                    documentRequest});
        return ((documentReturnType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsendDocument(documentType documentRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sendDocument", new object[] {
                    documentRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public documentReturnType EndsendDocument(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((documentReturnType)(results[0]));
    }
    
    /// <remarks/>
    public void sendDocumentAsync(documentType documentRequest) {
        this.sendDocumentAsync(documentRequest, null);
    }
    
    /// <remarks/>
    public void sendDocumentAsync(documentType documentRequest, object userState) {
        if ((this.sendDocumentOperationCompleted == null)) {
            this.sendDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendDocumentOperationCompleted);
        }
        this.InvokeAsync("sendDocument", new object[] {
                    documentRequest}, this.sendDocumentOperationCompleted, userState);
    }
    
    private void OnsendDocumentOperationCompleted(object arg) {
        if ((this.sendDocumentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sendDocumentCompleted(this, new sendDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getApplicationResponse", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("getAppRespResponse", Namespace="http://gib.gov.tr/vedop3/eFatura")]
    public getAppRespResponseType getApplicationResponse([System.Xml.Serialization.XmlElementAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")] getAppRespRequestType getAppRespRequest) {
        object[] results = this.Invoke("getApplicationResponse", new object[] {
                    getAppRespRequest});
        return ((getAppRespResponseType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetApplicationResponse(getAppRespRequestType getAppRespRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getApplicationResponse", new object[] {
                    getAppRespRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public getAppRespResponseType EndgetApplicationResponse(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((getAppRespResponseType)(results[0]));
    }
    
    /// <remarks/>
    public void getApplicationResponseAsync(getAppRespRequestType getAppRespRequest) {
        this.getApplicationResponseAsync(getAppRespRequest, null);
    }
    
    /// <remarks/>
    public void getApplicationResponseAsync(getAppRespRequestType getAppRespRequest, object userState) {
        if ((this.getApplicationResponseOperationCompleted == null)) {
            this.getApplicationResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetApplicationResponseOperationCompleted);
        }
        this.InvokeAsync("getApplicationResponse", new object[] {
                    getAppRespRequest}, this.getApplicationResponseOperationCompleted, userState);
    }
    
    private void OngetApplicationResponseOperationCompleted(object arg) {
        if ((this.getApplicationResponseCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getApplicationResponseCompleted(this, new getApplicationResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")]
public partial class documentType {
    
    private string fileNameField;
    
    private base64Binary binaryDataField;
    
    private string hashField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public base64Binary binaryData {
        get {
            return this.binaryDataField;
        }
        set {
            this.binaryDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hash {
        get {
            return this.hashField;
        }
        set {
            this.hashField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
public partial class base64Binary {
    
    private string contentTypeField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string contentType {
        get {
            return this.contentTypeField;
        }
        set {
            this.contentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")]
public partial class getAppRespResponseType {
    
    private string applicationResponseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string applicationResponse {
        get {
            return this.applicationResponseField;
        }
        set {
            this.applicationResponseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")]
public partial class getAppRespRequestType {
    
    private string instanceIdentifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string instanceIdentifier {
        get {
            return this.instanceIdentifierField;
        }
        set {
            this.instanceIdentifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gib.gov.tr/vedop3/eFatura")]
public partial class documentReturnType {
    
    private string msgField;
    
    private string hashField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string msg {
        get {
            return this.msgField;
        }
        set {
            this.msgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hash {
        get {
            return this.hashField;
        }
        set {
            this.hashField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void sendDocumentCompletedEventHandler(object sender, sendDocumentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sendDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sendDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public documentReturnType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((documentReturnType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void getApplicationResponseCompletedEventHandler(object sender, getApplicationResponseCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getApplicationResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getApplicationResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public getAppRespResponseType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((getAppRespResponseType)(this.results[0]));
        }
    }
}
